travis:
  secure:
    BINSTAR_TOKEN: tiP1S7QRlEFbIWNiaYt6gIn+bS5C0Ze/aB+SvX+XdNFxlDouhN4EHSYcELV91vrxbcPO2+f60e1fbFVrnthJr41c/TZa0R0zgWRUEllU0pbXRy9em2EKa+rz6jIfwliCLjOjLFGYyJUyaFHMzqj/0upUv2eRxHcNpz4z+zPCuoZeo+ibPJFW90thYK+fgQ6QFRbDCSKhpk51U53oeZMhOAKHMdN5oez3TIVbzzkHoUitZmqf8k6lO8qGtuhK6pBzlSihkK5s6KbU8P5WQQkKSkthwBJNxTbumhXUEfRd+aNT8Icqft9F4hIvttpb1tnoYadnnv4NXgOwcgpmOtyIr03MNAnskmL9J6I6YLIWLGgWnsTAu/kNJFltxQU99iDaXrZyWBEW69SK9AUXjUqzMf/btT23xzn4DDL1QncqQd+Zl9DWH/L8HsYL8L5JFuHdBmutWeVxZEMZqxg0y4Y/kJz/1xOoYlkSUViqYPlp9iZtJAJDHdPY2XKyi7khhLc/c+kYtFtmDvQ0Ku6xdkyVS4QasM0BdhlMxxotQxz4VPgE5N9CmkzVwwQbnMlfHOn20Yd+tTuGz5D1ujb5RmtIO7T7oL73qGDWPS/DvTe3u4U3Sphmtgexpko7ffyoB1jT+Co4qO9ZmLm1qWhyAHVDfwZDDy2NKRkclMnim4nZHyU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
